Don't use Maxmind licenses directly in Dockerfiles (#322)
* Use env variable for maxmind license key in Dockerfiles

* Adjust geoip tests to match actual values

* Don't fail in regression docker build or tests if maxmind dbs are not available

* Use a test mmdb file for logstash image if no maxmind license

* Remove geoip from wforce docker image and config

diff --git a/docker/logstash/Dockerfile b/docker/logstash/Dockerfile
--- a/docker/logstash/Dockerfile
+++ b/docker/logstash/Dockerfile
@@ -4,10 +4,13 @@ USER root
 RUN yum install -y wget
 RUN mkdir -p /usr/share/logstash/geoip
 RUN chown -R logstash:logstash /usr/share/logstash/geoip
-RUN wget -O GeoLite2-City.mmdb.tar.gz "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=SPdi9BhAhMj6oOpw&suffix=tar.gz"
-RUN gunzip GeoLite2-City.mmdb.tar.gz
-RUN tar xvf GeoLite2-City.mmdb.tar
-RUN mv GeoLite2*/GeoLite2-City.mmdb /usr/share/logstash/geoip
+ARG MAXMIND_LICENSE_KEY
+# Don't fail if license key isn't set
+COPY geoip/GeoIP2-City-Test.mmdb /usr/share/logstash/geoip/GeoLite2-City.mmdb
+RUN wget -O GeoLite2-City.mmdb.tar.gz "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=${MAXMIND_LICENSE_KEY}&suffix=tar.gz" || true
+RUN gunzip GeoLite2-City.mmdb.tar.gz || true
+RUN tar xvf GeoLite2-City.mmdb.tar || true
+RUN mv GeoLite2*/GeoLite2-City.mmdb /usr/share/logstash/geoip || true
 USER logstash
 
 RUN logstash-plugin install logstash-input-udp
